#!/bin/sh
#
# openscada        Starts openscada.
#

export OSCADA_ProjName=kium
export LANG=ru_RU.UTF-8

umask 077

start() {
	printf "Starting openscada: "
	openscada_start &
	touch /var/lock/openscada
	echo "OK"
}
stop() {
	printf "Stopping openscada: "
	killall openscada
	rm -f /var/lock/openscada
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

